"""Allow nullable GPU specifications

Revision ID: 08c023c418e5
Revises: eb17db90d7ab
Create Date: 2026-10-03 19:57:49.659613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c023c418e5'
down_revision: Union[str, Sequence[str], None] = 'eb17db90d7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gpu', 'core_clock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gpu', 'boost_clock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gpu', 'length',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gpu', 'length',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('gpu', 'boost_clock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('gpu', 'core_clock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
