"""initial schema

Revision ID: 14c42a19a331
Revises: 
Create Date: 2026-09-22 03:08:05.665415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c42a19a331'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpu',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('core_count', sa.Integer(), nullable=False),
    sa.Column('core_clock', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('boost_clock', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('microarchitecture', sa.String(length=100), nullable=False),
    sa.Column('tdp', sa.Integer(), nullable=False),
    sa.Column('graphics', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('gpu',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('chipset', sa.String(length=150), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('core_clock', sa.Integer(), nullable=False),
    sa.Column('boost_clock', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu')
    op.drop_table('cpu')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
