"""Allow nullable CPU boost clock

Revision ID: c0e47d5db444
Revises: 14c42a19a331
Create Date: 2026-09-23 00:12:21.643470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e47d5db444'
down_revision: Union[str, Sequence[str], None] = '14c42a19a331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cpu', 'boost_clock',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cpu', 'boost_clock',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    # ### end Alembic commands ###
